### ISSUE TITLE
'Create custom gift' incorrectly links to 'Create custom task'

### ISSUE THREAD

**Issue by gawdzilla-dev** [lvshuncn/habit_score_reward#1]
In the "Select a preset gift" section, if the query has no results, it provides a link to "Create a custom gift" (seen below).  However, this specific link always links to "Create a custom task" instead.

![image](https://github.com/user-attachments/assets/7a67aec5-fa78-4618-8e22-f9e20f1645d9)

![image](https://github.com/user-attachments/assets/f56688e9-7dda-45d1-8da0-91d11a68aa1a)

**Comment by lvshuncn** [comment]
Thank you for your feedback. We will fix this issue in the next release.

**Comment by lvshuncn** [comment]
By the way, do you have a PRO subscription? To thank you for your feedback, we can give you a redemption code for an annual subscription.

**Comment by gawdzilla-dev** [comment]
Not yet -- just on the free trial as of last night.   I would very much appreciate such a code.   Thank you for a well-designed app, as well as the fast response.

**Comment by lvshuncn** [comment]
> Not yet -- just on the free trial as of last night. I would very much appreciate such a code. Thank you for a well-designed app, as well as the fast response.

Thank you very much, we're happy that you like our app. Could you please send an email to lvshun@live.cn with the subject "Promotional code"? In the email, let us know whether you are using iOS or Android, and we will reply with an annual subscription code as soon as we receive your email.

**Comment by lvshuncn** [comment]
Fixed in 1.13.4

**Comment by lvshuncn** [comment]
Fixed in 1.13.4, please upgrade to the latest version
